apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
  name: webhook-service
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: controller-webhook