apiVersion: azuredevops.krateo.io/v1alpha1
kind: FeedPermission
metadata:
  name: feedpermission-sample
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  deletionPolicy: Orphan
  projectRef:
    name: teamproject
    namespace: default
  feed: test-feed-4
  user:
    type: build-service
    role: reader
    projectRef:
      name: teamproject-sample
      namespace: default
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
