apiVersion: azuredevops.krateo.io/v1alpha1
kind: GitRepository
metadata:
  name: gitrepository-sample
spec:
  name: krateo-test-default-branch-param
  initialize: true
  projectRef:
    name: teamproject-sample
    namespace: default
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
