apiVersion: azuredevops.krateo.io/v1alpha1
kind: Run
metadata:
  name: run-sample
spec:
  pipelineRef:
    name: pipeline-sample
    namespace: default
  connectorConfigRef:
    namespace: default
    name: connectorconfig-sample
