apiVersion: azuredevops.krateo.io/v1alpha1
kind: TeamProject
metadata:
  name: team-sample
spec:
  apiUrl: https://dev.azure.com
  verbose: false
  credentials:
    secretRef:
      namespace: default
      name: azuredevops-secret
      key: token
  org: kiratech-bancasella
  name: Project n.7 created by Krateo 
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit
  visibility: private
  capabilities:
    versioncontrol:
      sourceControlType: Git
    processTemplate:
      templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45
  