//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Kiratech SPA.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/krateoplatformops/provider-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIVersionConfig) DeepCopyInto(out *APIVersionConfig) {
	*out = *in
	if in.CheckConfigurations != nil {
		in, out := &in.CheckConfigurations, &out.CheckConfigurations
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(string)
		**out = **in
	}
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = new(string)
		**out = **in
	}
	if in.Feeds != nil {
		in, out := &in.Feeds, &out.Feeds
		*out = new(string)
		**out = **in
	}
	if in.FeedPermissions != nil {
		in, out := &in.FeedPermissions, &out.FeedPermissions
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new(string)
		**out = **in
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = new(string)
		**out = **in
	}
	if in.PipelinePermissions != nil {
		in, out := &in.PipelinePermissions, &out.PipelinePermissions
		*out = new(string)
		**out = **in
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(string)
		**out = **in
	}
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = new(string)
		**out = **in
	}
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = new(string)
		**out = **in
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPermissions != nil {
		in, out := &in.RepositoryPermissions, &out.RepositoryPermissions
		*out = new(string)
		**out = **in
	}
	if in.Runs != nil {
		in, out := &in.Runs, &out.Runs
		*out = new(string)
		**out = **in
	}
	if in.SecureFiles != nil {
		in, out := &in.SecureFiles, &out.SecureFiles
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(string)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(string)
		**out = **in
	}
	if in.VariableGroups != nil {
		in, out := &in.VariableGroups, &out.VariableGroups
		*out = new(string)
		**out = **in
	}
	if in.Descriptors != nil {
		in, out := &in.Descriptors, &out.Descriptors
		*out = new(string)
		**out = **in
	}
	if in.Memberships != nil {
		in, out := &in.Memberships, &out.Memberships
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIVersionConfig.
func (in *APIVersionConfig) DeepCopy() *APIVersionConfig {
	if in == nil {
		return nil
	}
	out := new(APIVersionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiUrl) DeepCopyInto(out *ApiUrl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiUrl.
func (in *ApiUrl) DeepCopy() *ApiUrl {
	if in == nil {
		return nil
	}
	out := new(ApiUrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConfig) DeepCopyInto(out *ConnectorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConfig.
func (in *ConnectorConfig) DeepCopy() *ConnectorConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConfigList) DeepCopyInto(out *ConnectorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConfigList.
func (in *ConnectorConfigList) DeepCopy() *ConnectorConfigList {
	if in == nil {
		return nil
	}
	out := new(ConnectorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorConfigSpec) DeepCopyInto(out *ConnectorConfigSpec) {
	*out = *in
	if in.ApiUrls != nil {
		in, out := &in.ApiUrls, &out.ApiUrls
		*out = new(ApiUrl)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(v1.CredentialSelectors)
		(*in).DeepCopyInto(*out)
	}
	if in.APIVersionConfig != nil {
		in, out := &in.APIVersionConfig, &out.APIVersionConfig
		*out = new(APIVersionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorConfigSpec.
func (in *ConnectorConfigSpec) DeepCopy() *ConnectorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reference) DeepCopyInto(out *Reference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}
